# Generated by Django 5.2.7 on 2025-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'درانتظازپرداخت'), ('Processing', 'درحال پردازش'), ('Shipped', 'ارسال شده به پست'), ('delivered', 'تحویل شد')], default='Pending', max_length=50),
        ),
    ]
