# Generated by Django 5.2.7 on 2025-11-13 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_profile_old_cart_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 11, 13, 22, 49, 19, 376380)),
        ),
    ]
